ClienteMarWPF.DataAccess/Services/Helpers/SoapClientRepository.cs
ClienteMarWPF.DataAccess/Services/SorteosDataService.cs
ClienteMarWPF.Domain/Models/Dtos/SorteosDTO.cs
ClienteMarWPF.Domain/Services/SorteosService/ISorteosService.cs
ClienteMarWPF.UI/App.xaml
ClienteMarWPF.UI/Modules/Recargas/Modal/DialogImprimirTicketViewModel.cs
ClienteMarWPF.UI/Modules/Reporte/ReporteViewModel.cs
ClienteMarWPF.UI/Modules/Sorteos/Modal/ValidarPagoTicket.xaml
ClienteMarWPF.UI/Modules/Sorteos/Modal/ValidarPagoTicket.xaml.cs
ClienteMarWPF.UI/Modules/Sorteos/Modal/ValidarPagoTicketViewModel.cs
ClienteMarWPF.UI/Modules/Sorteos/SorteosView.xaml
ClienteMarWPF.UI/Modules/Sorteos/SorteosView.xaml.cs
ClienteMarWPF.UI/Modules/Sorteos/SorteosViewModel.cs
ClienteMarWPF.UI/State/PinterConfig/ModelsPrinJobs.cs
ClienteMarWPF.UI/State/PinterConfig/PrintJobs.cs
ClienteMarWPF.UI/State/PinterConfig/TicketTemplateHelper.cs
ClienteMarWPF.UI/ViewModels/Commands/Recargas/DialogConfirmTicketCommand.cs
ClienteMarWPF.UI/ViewModels/Commands/Recargas/SendRecargaCommand.cs
ClienteMarWPF.UI/ViewModels/Commands/Sorteos/CopiarTicketCommand.cs
ClienteMarWPF.UI/ViewModels/Commands/Sorteos/GetListadoTicketsCommand.cs
ClienteMarWPF.UI/ViewModels/Commands/Sorteos/PagarTicketCommand.cs
ClienteMarWPF.UI/ViewModels/Commands/Sorteos/RealizarApuestaCommand.cs
ClienteMarWPF.UI/ViewModels/Commands/Sorteos/ReimprimirTicketCommand.cs
ClienteMarWPF.UI/ViewModels/ModelObservable/SorteosObservable.cs

copiar ticket
reimprimir ticket
creacion ticket en jugadas

Implementaciones sorteos

---

ClienteMarWPF.DataAccess/ClienteMarWPF.DataAccess.csproj
ClienteMarWPF.DataAccess/Services/Helpers/SoapClientRepository.cs
ClienteMarWPF.UI/Modules/Sorteos/Modal/ValidarPagoTicket.xaml
ClienteMarWPF.UI/ViewModels/Commands/Sorteos/GetListadoTicketsCommand.cs
Flujo.DataAccess/Flujo.DataAccess.csproj
MAR.BusinessLogic/MAR.BusinessLogic.csproj
MAR.DataAccess/MAR.DataAccess.csproj
MAR.WebServices7/MAR.WebServices7.vbproj

Cambios1632021

---

ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml.cs
ClienteMarWPFWin7.UI/Views/WindowsModals/CombinacionWindowsModal.xaml.cs

Cambios sorteos/timer

---

ClienteMarWPFWin7.UI/MainWindow.xaml
ClienteMarWPFWin7.UI/Modules/Recargas/RecargasView.xaml.cs

Fluidez recargas

---

ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml.cs

Sorteos cambios

---

ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml.cs
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosViewModel.cs

Cambios Listado y super pales

---

ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml.cs

Cambios Listado sorteos

---

ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml.cs

Cambios sorteos 03052021

---

ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml.cs

Cambios de tab

---

ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml.cs

Cambios teclas sorteos

---

ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml.cs

Cambios y mejoras

---

ClienteMarWPFWin7.Data/Services/SorteosDataService.cs
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml.cs

Mejoras en super pales

---

ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml.cs

Combinado y detalles mejorados

---

ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml.cs

Botón eliminar y cambios de fluidez en sorteos

---

ClienteMarWPFWin7.UI/App.xaml
ClienteMarWPFWin7.UI/ClienteMarWPFWin7.UI.csproj
ClienteMarWPFWin7.UI/MainWindow.xaml.cs
ClienteMarWPFWin7.UI/Modules/EnLinea/EnLinea.xaml
ClienteMarWPFWin7.UI/Modules/EnLinea/EnLinea.xaml.cs
ClienteMarWPFWin7.UI/Modules/EnLinea/EnLineaViewModel.cs
ClienteMarWPFWin7.UI/ViewModels/Factories/ViewModelFactory.cs
ClienteMarWPFWin7.UI/Views/AttachedProperties/WebBrowserHelper.cs
ClienteMarWPFWin7.UI/Views/Controls/BarraNavegacionControl.xaml

Integracion WEB BROSWER

---

ClienteMarWPFWin7.Domain/Enums/AppEnums.cs
ClienteMarWPFWin7.UI/Extensions/AppExtension.cs

Cambios que faltaron

---

ClienteMarWPFWin7.UI/Modules/Home/HomeView.xaml

Cambio de descripcion

---

ClienteMarWPFWin7.Data/Services/CajaDataService.cs
ClienteMarWPFWin7.Domain/Enums/AppEnums.cs
ClienteMarWPFWin7.Domain/Services/CajaService/ICajaService.cs
MAR.BusinessLogic/Code/ControlEfectivo/CajaLogic.cs
MAR.DataAccess/ControlEfectivoRepositories/CajaRepository.cs
MAR.DataAccess/ControlEfectivoRepositories/Helpers/BancaHelper.cs
MAR.DataAccess/ControlEfectivoRepositories/Helpers/CajaHelper.cs
MAR.WebServices7/mar-flujo.asmx.vb

Actualizacion del total vendido de productos se le agrego las recargas

Recargas incluidas 

---

ClienteMarWPFWin7.UI/App.xaml
ClienteMarWPFWin7.UI/Modules/Sorteos/Modal/ValidarPagoTicket.xaml
ClienteMarWPFWin7.UI/Modules/Sorteos/Modal/ValidarPagoTicket.xaml.cs
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml

Bloqueo accion de re-impresion por 5 Seg

Bloqueo de Re-Impresion

---

ClienteMarWPFWin7.UI/ClienteMarWPFWin7.UI.csproj
ClienteMarWPFWin7.UI/Modules/Sorteos/Modal/ValidarPagoTicket.xaml
ClienteMarWPFWin7.UI/Modules/Sorteos/Modal/ValidarPagoTicket.xaml.cs
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml

Bloqueo de Boton de Anulacion y Loading

Anulacion Bloqueo

---

ClienteMarWPFWin7.UI/Modules/Sorteos/Modal/ValidarPagoTicket.xaml.cs
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml
ClienteMarWPFWin7.UI/ViewModels/Commands/Sorteos/CopiarTicketCommand.cs

Quitar bloqueo de botones

---

ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml

Reverts LuiggieGN/ClienteMarWPF#163

Revert "Cambios botones"

---

ClienteMarWPFWin7.UI/MainWindow.xaml.cs
ClienteMarWPFWin7.UI/Views/Controls/BarraNavegacionControl.xaml

Logica de los F

---

ClienteMarWPFWin7.UI/App.xaml.cs
ClienteMarWPFWin7.UI/ClienteMarWPFWin7.UI.csproj
ClienteMarWPFWin7.UI/Extensions/FileExtension.cs
ClienteMarWPFWin7.UI/Modules/Configuracion/ConfiguracionViewModel.cs
ClienteMarWPFWin7.UI/State/LocalClientSetting/LocalClientBase.cs
ClienteMarWPFWin7.UI/State/LocalClientSetting/LocalClientSettingStore.cs

Creando archivos requeridos BackUp

BackUp Restored

---

ClienteMarWPFWin7.UI/ClienteMarWPFWin7.UI.csproj
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/CuadreLogin/CuadreLoginView.xaml
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/CuadreLogin/CuadreLoginView.xaml.cs
MAR.DataAccess/ControlEfectivoRepositories/BancaRepository.cs

Se habilito Enter y Focus en el primer input

Cuadre login

---

ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/CuadreLogin/CuadreLoginView.xaml
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/CuadreLogin/CuadreLoginView.xaml.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/Login/LoginCommand.cs

Detectar tacla ESC en modal Cuadre Del Dia para cerrar ventana

Habilitar Tecla ESC modal Cuadre Del Dia

---

ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/Cuadre/CuadreView.xaml
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/Cuadre/CuadreView.xaml.cs

Cerrar ventana "Cuadre" con tecla ESC

Modal Cuadre Cerrar con tecla ESC

---

ClienteMarWPFWin7.UI/ViewModels/Commands/FlujoEfectivo/Cuadre/Cuadre/RegistrarCuadreCommand.cs

Informacion sesitiva del cliente fue removida

Se removio informacion  sensitiva

---

ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/Cuadre/CuadreViewModel.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/FlujoEfectivo/Cuadre/Cuadre/RegistrarCuadreCommand.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/FlujoEfectivo/Cuadre/Cuadre/SetRecomendacionCommand.cs
ClienteMarWPFWin7.UI/Views/Controls/BarraNavegacionControl.xaml

Cambiar balance por monto contado

---

ClienteMarWPFWin7.UI/Extensions/ObservableExtensions.cs
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Movimiento/Views/View3/ConsultaMovimientoView.xaml

Se corrio descripcion removiendo tags de html

Correccion Descripcion de Movimiento

---

ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/Cuadre/CuadreView.xaml
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/Cuadre/CuadreView.xaml.cs
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/Cuadre/CuadreViewModel.cs

Habilitar Teclas Enter, TAB y Flecha para seleccionar input con fluidez

---

ClienteMarWPFWin7.Data/ClienteMarWPFWin7.Data.csproj
ClienteMarWPFWin7.Data/Services/ServerDataService.cs
ClienteMarWPFWin7.Domain/ClienteMarWPFWin7.Domain.csproj
ClienteMarWPFWin7.Domain/Services/ServerService/IServerService.cs
ClienteMarWPFWin7.UI/Extensions/AppExtension.cs
ClienteMarWPFWin7.UI/Extensions/FileExtension.cs
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/Cuadre/CuadreView.xaml.cs
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/Cuadre/ViewModels/ArqueoResultanteViewModel.cs
ClienteMarWPFWin7.UI/State/LocalClientSetting/ILocalClientSettingStore.cs
ClienteMarWPFWin7.UI/State/LocalClientSetting/LocalClientBase.cs
ClienteMarWPFWin7.UI/State/LocalClientSetting/LocalClientSettingStore.cs

Escribir server txt file y hacer backup del mismo

Feature Write Server Txt File

---

ClienteMarWPFWin7.UI/ClienteMarWPFWin7.UI.csproj
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/Cuadre/CuadreView.xaml
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/Cuadre/CuadreView.xaml.cs
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/Cuadre/CuadreViewModel.cs
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/CuadreDesglose/DesgloseWindows.xaml
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/CuadreDesglose/DesgloseWindows.xaml.cs
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Movimiento/MovimientoView.xaml.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/FlujoEfectivo/Cuadre/Cuadre/AbrirDesgloseCommand.cs

Fluidez del modulo de cuadre completada

Cuadre Fluidez Al 100

---

ClienteMarWPFWin7.Domain/Models/Dtos/BancaConfiguracionDTO.cs
ClienteMarWPFWin7.UI/ClienteMarWPFWin7.UI.csproj
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/Cuadre/Modal/DialogoTokenViewModel.cs
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Movimiento/Modal/DialogoTokenViewModel.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/FlujoEfectivo/Cuadre/Cuadre/RegistrarCuadreCommand.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/FlujoEfectivo/Movimiento/DesdeHastaView/AbrirModalTokenCommand.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/FlujoEfectivo/Movimiento/DesdeHastaView/RegistrarTransferenciaCommand.cs
MAR.DataAccess/ControlEfectivoRepositories/Helpers/BancaHelper.cs
MAR.DataAccess/Tables/ControlEfectivoDTOs/ControlEfectivoDTO.cs

Se agrego lógica de cuadre genérico

Token Generico Logica

---

ClienteMarWPFWin7.UI/Modules/Sorteos/Modal/ValidarPagoTicket.xaml
ClienteMarWPFWin7.UI/Modules/Sorteos/Modal/ValidarPagoTicket.xaml.cs

Correcion Copiar Tickets

---

ClienteMarWPFWin7.UI/ClienteMarWPFWin7.UI.csproj
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml.cs
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosViewModel.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/Sorteos/RealizarApuestaCommand.cs

Vendidos Hoy

---

ClienteMarWPFWin7.UI/ClienteMarWPFWin7.UI.csproj
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml.cs

Feature timerupgradetime

---

ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml.cs
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosViewModel.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/Sorteos/AnularTicketCommand.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/Sorteos/PagarTicketCommand.cs

Refrescar Balance

---

ClienteMarWPFWin7.UI/ClienteMarWPFWin7.UI.csproj
ClienteMarWPFWin7.UI/ViewModels/Commands/Recargas/SendRecargaCommand.cs

Balance refrescar

---

ClienteMarWPFWin7.UI/ClienteMarWPFWin7.UI.csproj
ClienteMarWPFWin7.UI/Views/Controls/BarraNavegacionControl.xaml

Se actualizo la barra denavegacion

Barra de Navegacion

---

ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/Cuadre/CuadreView.xaml
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/Cuadre/CuadreViewModel.cs
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Movimiento/MovimientoView.xaml.cs
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Movimiento/Views/View2/DesdeHastaView.xaml
ClienteMarWPFWin7.UI/ViewModels/Commands/FlujoEfectivo/Cuadre/Cuadre/InitCuadreCommand.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/FlujoEfectivo/Cuadre/Cuadre/RegistrarCuadreCommand.cs

Ocultar recomendacion hasta que se ingrese el monto contado

Ocultar Recomendacion

---

ClienteMarWPFWin7.UI/Modules/Mensajeria/MensajeriaView.xaml
ClienteMarWPFWin7.UI/Modules/Mensajeria/MensajeriaView.xaml.cs
ClienteMarWPFWin7.UI/Modules/Mensajeria/MensajeriaViewModel.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/MainWindow/LogoutCommand.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/MainWindow/UpdateCurrentViewModelCommand .cs
ClienteMarWPFWin7.UI/ViewModels/Commands/Mensajes/GetMensajesCommand.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/Mensajes/SendMensajeCommand.cs

Mensaje Parte 1

---

ClienteMarWPFWin7.UI/ClienteMarWPFWin7.UI.csproj
ClienteMarWPFWin7.UI/Converters/Chat/ChatMensajeAlineacionConverter.cs
ClienteMarWPFWin7.UI/Converters/Chat/ChatMensajeBackgroundConverter.cs
ClienteMarWPFWin7.UI/Extensions/ObservableExtensions.cs
ClienteMarWPFWin7.UI/Modules/Mensajeria/MensajeriaView.xaml
ClienteMarWPFWin7.UI/Modules/Mensajeria/MensajeriaViewModel.cs
ClienteMarWPFWin7.UI/StartUp/Resources/Style/Colors.xaml
ClienteMarWPFWin7.UI/ViewModels/Commands/Mensajes/GetMensajesCommand.cs
ClienteMarWPFWin7.UI/ViewModels/ModelObservable/ChatMensajeObservable.cs

Chat Direccion y Estilos

---

ClienteMarWPFWin7.UI/StartUp/Resources/Style/Colors.xaml

Feature mensaje parte2

---

ClienteMarWPFWin7.UI/Converters/Chat/ChatMensajeAlineacionConverter.cs
ClienteMarWPFWin7.UI/Modules/Mensajeria/MensajeriaView.xaml
ClienteMarWPFWin7.UI/Modules/Mensajeria/MensajeriaViewModel.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/Mensajes/GetMensajesCommand.cs

Se le agrego la hora

---

ClienteMarWPFWin7.UI/ClienteMarWPFWin7.UI.csproj
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/Cuadre/Modal/DialogoToken.xaml
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Cuadre/Windows/Cuadre/Modal/DialogoToken.xaml.cs
ClienteMarWPFWin7.UI/Modules/FlujoEfectivo/Movimiento/Views/View2/DesdeHastaView.xaml.cs
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml
ClienteMarWPFWin7.UI/ViewModels/Commands/FlujoEfectivo/Cuadre/Cuadre/RegistrarCuadreCommand.cs

Colocar loading

---

ClienteMarWPFWin7.UI/ClienteMarWPFWin7.UI.csproj
ClienteMarWPFWin7.UI/Extensions/AppExtension.cs
ClienteMarWPFWin7.UI/Extensions/LocalClientSettingExtension.cs

OldSchool hardwarekey

---

ClienteMarWPFWin7.UI/Extensions/AppExtension.cs
ClienteMarWPFWin7.UI/Modules/PegaMas/PegaMasViewModel.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/PegaMas/VenderCommand.cs

Pega Mas Parte 3

---

ClienteMarWPFWin7.UI/Modules/PegaMas/PegaMasView.xaml
ClienteMarWPFWin7.UI/Modules/PegaMas/PegaMasView.xaml.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/PegaMas/VenderCommand.cs

Pega Mas Parte4

---

ClienteMarWPFWin7.Data/Services/AccountDataService.cs
ClienteMarWPFWin7.Data/Services/CincoMinutosDataService.cs
ClienteMarWPFWin7.Data/SessionGlobals.cs
ClienteMarWPFWin7.Domain/ClienteMarWPFWin7.Domain.csproj
ClienteMarWPFWin7.Domain/Enums/CincoMinutosEnum.cs
ClienteMarWPFWin7.Domain/Models/Dtos/AnulaApuestaResponseModel.cs
ClienteMarWPFWin7.Domain/Models/Dtos/CincoMinutosRequestModel.cs
ClienteMarWPFWin7.Domain/Models/Dtos/ConsultaPagoResponseModel.cs
ClienteMarWPFWin7.UI/ClienteMarWPFWin7.UI.csproj
ClienteMarWPFWin7.UI/Modules/CincoMinutos/ConsultaCincoMinutos.xaml
ClienteMarWPFWin7.UI/Modules/CincoMinutos/ConsultaCincoMinutos.xaml.cs
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/Sorteos/RealizarApuestaCommand.cs

Cambios camión millonario - Noe Medina

Agregando cambios de camión millonarios

---

ClienteMarWPFWin7.UI/Modules/PegaMas/PegaMasView.xaml
ClienteMarWPFWin7.UI/Modules/PegaMas/PegaMasView.xaml.cs
ClienteMarWPFWin7.UI/Modules/PegaMas/PegaMasViewModel.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/PegaMas/AgregaApuestaCommand.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/PegaMas/VenderCommand.cs
ClienteMarWPFWin7.UI/ViewModels/ModelObservable/PegaMasApuestaObservable.cs

Pega Mas Parte 5

---

ClienteMarWPFWin7.UI/ClienteMarWPFWin7.UI.csproj
ClienteMarWPFWin7.UI/Modules/PegaMas/PegaMasView.xaml
ClienteMarWPFWin7.UI/Modules/PegaMas/PegaMasView.xaml.cs
ClienteMarWPFWin7.UI/Modules/Sorteos/SorteosView.xaml.cs
ClienteMarWPFWin7.UI/ViewModels/Commands/PegaMas/RemoverJugadasCommand.cs

Pega Mas Anulacion

---

ClienteMarWPFWin7.UI/MainWindowViewModel.cs
ClienteMarWPFWin7.UI/Modules/PegaMas/PegaMasView.xaml
ClienteMarWPFWin7.UI/ViewModels/Commands/Login/LoginCommand.cs

Bug Mensaje Resuelto
